environment: dev
project_name: aws-base-infra
prefix: sigmoid
region: ap-northeast-2
aws_profile: default
managed_by: Sigmoid
vpc_cidr: 10.0.0.0/16

bastion_instance_type: t3.small
bastion_key_name: ec2-kp

rds_engine: mysql
rds_engine_version: 8.0.42
rds_database_name: sigmoid_app
rds_port: 3306
rds_parameter_group_family: mysql8.0
rds_backup_window: 03:00-04:00
rds_maintenance_window: sun:05:00-sun:06:00
rds_cloudwatch_logs_exports:
  - error
  - slowquery
rds_performance_insights_enabled: false
rds_master_password: asdfjoiqqwjksdajhfk

ecs_repository_name: sigmoid-app
ecs_image_tag_mutability: MUTABLE
ecs_keep_last_n_images: 10
ecs_app_version: 1.0.2
